import { useState } from 'react';
import { useSupabaseClient } from '@supabase/auth-helpers-react';
import Layout from '../components/Layout.js';

export default function Page() {
  const supabase = useSupabaseClient();
  const [message, setMessage] = useState(null);

  const onSubmit = async function (e) {
    e.preventDefault();
    const data = new FormData(e.target);
    const { error } = await supabase.from('contacts').insert(Object.fromEntries(data), { returning: 'minimal' });
    if (error) {
      setMessage('Sorry, an unexpected error occurred.');
    } else {
      setMessage(
        <div>
          <h2 className="text-center mt-3 text-green-1">Confirmation</h2>
          <p className="text-green-hover">Thank you for contacting us. We will get back to you promptly.</p>
        </div>
      );
    }
  };

  return (
    <Layout title="Contacts" description="Generated by create next app">
      <h1 className="text-3xl font-extrabold mb-4 text-center mt-4 text-green-1">Contact Us</h1>
      <br /> 
      <br /> 
      <div className="flex flex-col lg:flex-row items-center justify-center">
        {/* Partie gauche (Questions & Réponses) */}
        <div className="lg:w-1/2 p-4 bg-green-1 text-white">
          <h2 className="text-xl text-gray-800 font-bold mb-4">Have a question? Maybe the answer is already here:</h2>
          <ul className="list-disc pl-4 text-white">
            <li className="mb-4 ">
              <h3 className="text-green-hover font-bold">How can I submit a recipe to be added to your site?</h3>
              <p>
                If you have a recipe you'd like to share, you simply need to create an account or log in with your GitHub account and go to your Profile page. There, you can click on "add an article." Make sure to include all the details of the recipe, including the ingredients, preparation steps, and a photo if possible.
              </p>
            </li>
            <li className="mb-4">
              <h3 className="text-green-hover font-bold">How does the "Random Meals" category work?</h3>
              <p>
                Our "Random Meals" category generates a random recipe from those available on our platform. It's a great way to discover new recipes and get inspiration for your next meals. Just click on the "Random Meals" button, and a selection of dishes will appear. Check out the recipe for the one that looks most appealing to you!
              </p>
            </li>
            <li className="mb-4">
              <h3 className="text-green-hover font-bold">Can I create a new category of dishes when adding one to the site?</h3>
              <p>
                Unfortunately, when you create an article, you need to choose the category of the dish from the list provided on the site. However, if you think it would be interesting to add a new category that is not currently available, you can suggest it to us by contacting us via the form on the left.
              </p>
            </li>
          </ul>
        </div>

        {/* Partie droite (Formulaire) */}
        <div className="lg:w-1/2 p-4 bg-beige-1">
          <form className="w-full max-w-md" onSubmit={onSubmit}>
            <div className="mb-4">
              <label className="block text-camel text-sm font-bold mb-2" htmlFor="firstname">
                First Name
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="firstname"
                type="text"
                name="firstname"
                required
              />
            </div>
            <div className="mb-4">
              <label className="block text-camel text-sm font-bold mb-2" htmlFor="lastname">
                Last Name
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="lastname"
                type="text"
                name="lastname"
                required
              />
            </div>
            <div className="mb-4">
              <label className="block text-camel text-sm font-bold mb-2" htmlFor="email">
                Email
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="email"
                type="text"
                name="email"
                required
              />
            </div>
            <div className="mb-4">
              <label className="block text-camel text-sm font-bold mb-2" htmlFor="message">
                Message
              </label>
              <textarea
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="message"
                name="message"
                required
              />
            </div>
            <div className="text-center">
              <button
                className="bg-green-hover hover:bg-green-1 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                type="submit"
              >
                Send
              </button>
            </div>
          </form>
          {message && (
            <div
              aria-label="Overflow below the drawer dialog"
              className="fixed inset-0 bg-black/80 flex items-center justify-center"
              onClick={() => setMessage(null)}
              role="dialog"
            >
              <div
                aria-label="Alert pane"
                className="max-h-[90vh] max-w-[95vw] overflow-auto p-4 prose bg-white"
              >
                {message}
              </div>
            </div>
          )}
        </div>
      </div>
    </Layout>
  );
}
