import { useState, useEffect } from 'react'
import Link from 'next/link'
import { ChevronRightIcon } from '@heroicons/react/20/solid'
import Layout from '../../components/Layout.js'
//import { useSupabaseClient } from '@supabase/auth-helpers-react'

export default function Articles() {
  const [articles, setArticles] = useState([])
  //const supabase = useSupabaseClient()
  
  useEffect(() => {
    (async () => {
      let { data, error} = await supabase
        .from('articles')
        .select(`id, name, description, price`)
      setArticles(data)
      console.log('Supabase query result:', { data, error});
    })()
  }, [])

  return (
    <Layout
      title="Articles"
      description="Generated by create next app"
    >
          <h1 className='wt-title'>
        List of articles
      </h1>
      <div className="not-prose -my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div className="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div className="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
            <table className="min-w-full divide-y divide-slate-300">
              <thead className="bg-slate-50">
                <tr>
                  <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-slate-900 sm:pl-6">
                    Name
                  </th>
                  <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">
                    Price
                  </th>
                  <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">
                    Description
                  </th>
                  <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 bg-white">
                {articles.map((article) => (
                  <tr key={article.id}>
                    <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">{article.name}</td>
                    <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">{article.price}</td>
                    <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">{article.description}</td>
                    <td>
                      <Link href={`articles/${article.id}`} className={"w-5 h-5 block bg-slate-200 hover:bg-blue-500 hover:text-white rounded-full"}>
                        <ChevronRightIcon className="h-5 w-5 " aria-hidden="true" />
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </Layout>
  )
}