import { useState, useEffect } from 'react'
import Link from 'next/link'
import { ChevronRightIcon } from '@heroicons/react/20/solid'
import Layout from '../../components/Layout.js'
import { useSupabaseClient } from '@supabase/auth-helpers-react'


export default function Users() {
    const [users, setUsers] = useState([]);
    const supabase = useSupabaseClient();

    useEffect(() => {
        const fetchUsers = async () => {
            try {
                const { data, error } = await supabase
                .from('users')
                .select('*');
                if (error) {
                    throw error;
                }
                setUsers(data || []);
            } catch (error) {
                console.error('Error fetching users:', error);
            }
        };

        fetchUsers();
    }, [supabase]);

    return (

        <Layout
            title="Admin users"
            description="Generated by create next app"
        >
            <h1 className='wt-title'>
                List of user messages
            </h1>
            <div className="not-prose -my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div className="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
                    <div className="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
                        <table className="min-w-full divide-y divide-slate-300">
                            <thead className="bg-slate-50">
                                <tr>
                                    <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-slate-900 sm:pl-6">
                                        Email
                                    </th>
                                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">
                                        id
                                    </th>
                                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">
                                        role
                                    </th>
                                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">
                                    </th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-200 bg-white">
                                {users.map((user) => (
                                    <tr key={user.email}>
                                        <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">{user.email}</td>
                                        <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">{user.id}</td>
                                        <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">{user.role}</td>
                                        <td>
                                            <Link href={`/admin/users/${user.id}`} className={"w-5 h-5 block bg-slate-200 hover:bg-blue-500 hover:text-white rounded-full"}>
                                                <ChevronRightIcon className="h-5 w-5 " aria-hidden="true" />
                                            </Link>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </Layout>
    )
}
