import { useState, useEffect } from 'react';
import Link from 'next/link';
import { ChevronRightIcon } from '@heroicons/react/outline';
import Layout from '../../components/Layout.js';
import { useSupabaseClient } from '@supabase/auth-helpers-react';

export default function Users() {
  const [users, setUsers] = useState([]);
  const supabase = useSupabaseClient();
  
  useEffect(() => {
    const fetchUsers = async () => {
      try {
        const { data: { users }, error } = await supabase.auth.admin.listUsers();

        if (error) {
          console.error('Erreur lors de la récupération des utilisateurs :', error.message);
          console.log(users)
          return;
        }

        console.log('Liste des utilisateurs récupérée avec succès :', users);
        setUsers(users);
      } catch (e) {
        console.error('Erreur inattendue lors de la récupération des utilisateurs :', e.message);
      }
    };

    fetchUsers();
  }, [supabase]);

  return (
    <Layout
      title="Users List"
      description="Generated by create next app"
    >
      <h1 className='wt-title'>
        List of users
      </h1>
      <div className="not-prose -my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div className="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
          <div className="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
            <table className="min-w-full divide-y divide-slate-300">
              <thead className="bg-slate-50">
                <tr>
                  <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-slate-900 sm:pl-6">
                    Firstname
                  </th>
                  <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">
                    Lastname
                  </th>
                  <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">
                    Email
                  </th>
                  <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 bg-white">
                {users.map((user) => (
                  <tr key={user.id}>
                    <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">{user.firstname}</td>
                    <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">{user.lastname}</td>
                    <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">{user.email}</td>
                    <td>
                      <Link href={`/admin/contacts/${user.id}`}>
                        <a className="w-5 h-5 block bg-slate-200 hover:bg-blue-500 hover:text-white rounded-full">
                          <ChevronRightIcon className="h-5 w-5" aria-hidden="true" />
                        </a>
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </Layout>
  );
}
