import Link from 'next/link'
import Layout from '../components/Layout.js'
import { useContext } from 'react';
import UserContext from '../components/UserContext'

export default function Page() {
  const {profile} = useContext(UserContext)
  return (
    <Layout
      description="Generated by create next app"
      >
      
      <h1 className='wt-title'>
        Welcome to web technologies!
      </h1>

      <ul>
        <li>
          <Link href="/articles">
            View our articles
          </Link>
        </li>
        <li>
          <Link href="/about">
            About us
          </Link>
        </li>
        <li>
          <Link href="/contacts">
            Contact us
          </Link>
        </li>
        <li>
          <Link href="https://github.com/adaltas/ece-webtech-2023-fall/blob/master/project-instructions.md">
            PROJECT INSTRUCTIONS
          </Link>
        </li>
      </ul>
    </Layout>
  )
}
