import { useState, useEffect } from 'react';
import { useSupabaseClient } from '@supabase/auth-helpers-react';
import md from 'markdown-it';
import Layout from '../../../components/Layout.js';

export default function Contacts({ id }) {
  const [contact, setContact] = useState(null);
  const supabase = useSupabaseClient();

  useEffect(() => {
    const fetchContact = async () => {
      const { data, error } = await supabase
        .from('contacts')
        .select('id, firstname, lastname, email, message')
        .eq('id', id)
        .single();

      console.log('Supabase query result:', { data, error });
        setContact(data);
      
    };

    fetchContact();
  }, [id]);
  return (
    <Layout title="Admin Contacts" description="Generated by create next app">
      <h1 className="wt-title">View a contact message</h1>
      {contact && (
        <div className="overflow-hidden divide-y divide-slate-200 shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <div className="bg-slate-50">
            <dl className="grid grid-cols-auto 1fr px-3 py-4 italic text-slate-500 pr-3">

              <dd>{contact.lastname} {contact.firstname}</dd>

              <dd>{contact.email}</dd>
            </dl>
          </div>
          <div className="px-3 py-10 bg-white">
            <div dangerouslySetInnerHTML={{ __html: md().render(contact.message) }} />
          </div>
        </div>
      )}
    </Layout>
  );
}

export async function getServerSideProps(context) {
  return {
    props: {
      id: context.params.id
    },
  }
}
